import json
from unittest.mock import patch

import pytest
from sqlalchemy import select

from app import create_app
from app.db import init_db, session_scope
from app.ingest import git
from app.llm import chat as chat_llm
from app.models import Repo, Tag


@pytest.fixture(scope="module")
def client():
    app = create_app()
    app.config["TESTING"] = True
    return app.test_client()


def test_health(client):
    body = client.get("/api/health").get_json()
    assert body["ok"] and body["db"] in {"sqlite", "postgres"} and body["generation_enabled"] is True


def test_create_repo_rejects_bad_url(client):
    r = client.post("/api/repos", json={"url": "ftp://nope"})
    assert r.status_code == 400


def test_graph_and_files_routes(client, fixture_repo, monkeypatch, seeded_repo):
    init_db()
    monkeypatch.setattr(git, "repo_dir", lambda owner, name: fixture_repo)
    with session_scope() as s:
        repo = s.scalar(select(Repo).where(Repo.url == "https://github.com/acme/demo"))
        assert repo is not None, "generated by test_generate"
        repo_id = repo.id
        tag = next(t for t in repo.tags if t.name == "v0.2.0")

    r = client.get(f"/api/repos/{repo_id}")
    assert r.status_code == 200
    assert [t["name"] for t in r.get_json()["tags"]] == ["v0.1.0", "v0.2.0"]
    assert all(t["has_graph"] for t in r.get_json()["tags"])

    g = client.get(f"/api/repos/{repo_id}/tags/v0.2.0/graph").get_json()
    assert "api-service" in g["tier2"]

    assert client.get(f"/api/repos/{repo_id}/tags/nope/graph").status_code == 404

    files = client.get(f"/api/repos/{repo_id}/tags/v0.2.0/files").get_json()
    assert {f["path"] for f in files} == {"README.md", "api/app.py", "requirements.txt", "worker/main.py"}

    content = client.get(f"/api/repos/{repo_id}/tags/v0.2.0/files", query_string={"path": "api/app.py"}).get_json()
    assert "Flask" in content["content"] and content["language"] == "python"

    assert client.get(f"/api/repos/{repo_id}/tags/v0.2.0/files", query_string={"path": "../etc/passwd"}).status_code == 404


def test_chat_streams_sse(client, seeded_repo):
    with session_scope() as s:
        repo = s.scalar(select(Repo).where(Repo.url == "https://github.com/acme/demo"))
        repo_id = repo.id

    def fake_stream(ctx, messages):
        assert "api-service" in ctx.architecture
        yield {"type": "text", "text": "Hello "}
        yield {"type": "text", "text": "world"}

    with patch.object(chat_llm, "stream_chat", side_effect=fake_stream):
        r = client.post("/api/chat", json={"repo_id": repo_id, "tag": "v0.2.0", "tier": 2, "system_id": "api-service", "messages": [{"role": "user", "content": "hi"}]})
    assert r.status_code == 200 and r.mimetype == "text/event-stream"
    events = [json.loads(line[6:]) for line in r.get_data(as_text=True).splitlines() if line.startswith("data: ")]
    assert [e["type"] for e in events] == ["text", "text", "done"]


def test_chat_tool_read_file(fixture_repo, monkeypatch, seeded_repo):
    monkeypatch.setattr(git, "repo_dir", lambda owner, name: fixture_repo)
    with session_scope() as s:
        tag = s.scalar(select(Tag).where(Tag.name == "v0.2.0"))
        ctx = chat_llm.ChatContext.from_tag(tag, tier=1, system_id=None, module_id=None, selected_node=None, open_file=None)
    text, err = chat_llm._run_tool(ctx, "read_file", {"path": "api/app.py", "start_line": 1, "end_line": 2})
    assert not err and "Flask" in text and "    3" not in text
    text, err = chat_llm._run_tool(ctx, "read_file", {"path": "../secret"})
    assert err
    text, err = chat_llm._run_tool(ctx, "list_files", {"query": "api"})
    assert text == "api/app.py"


def test_step_route_only_in_chunked_mode(client, seeded_repo):
    from app.config import Config
    from app.llm import generate as gen
    with session_scope() as s:
        repo = s.scalar(select(Repo).where(Repo.url == "https://github.com/acme/demo"))
        job_id = gen.create_job(repo.id, [repo.tags[0].id])
    assert client.post(f"/api/jobs/{job_id}/step").status_code == 409
    monkeypatch_mode = Config.GENERATION_MODE
    Config.GENERATION_MODE = "chunked"
    try:
        with patch.object(gen, "run_job_step", return_value=False) as m:
            body = client.post(f"/api/jobs/{job_id}/step").get_json()
            assert body["done"] is False and m.called
    finally:
        Config.GENERATION_MODE = monkeypatch_mode
